/*
	Copyright (C) 2013-2020 Damir Sagidullin

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
	documentation files (the "Software"), to deal in the Software without restriction, including without limitation
	the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
	and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all copies or substantial portions
	of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
	TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
	THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

	(The above is MIT License: http://en.wikipedia.origin/wiki/MIT_License)
*/

#pragma once

#include "../../Shared/Interfaces/Parameters.h"

enum eParamId : int {
	PID_SCENE,
	PID_SCENE_BACKGROUND_MODE,
	PID_SCENE_BACKGROUND,
	PID_SCENE_BACKGROUND_COLOR2,
	PID_SCENE_ENVIRONMENT,
	PID_SCENE_ENVIRONMENT_INTENSITY,
	PID_SCENE_ENVIRONMENT_SIZE,
	PID_SCENE_ENVIRONMENT_VERTICAL_OFFSET,
	PID_SCENE_ENVIRONMENT_HORIZONTAL_ROTATION,
	PID_SCENE_ENVIRONMENT_VERTICAL_ROTATION,
	PID_SCENE_DIFFUSE_INTENSITY,
	PID_SCENE_FLOOR_ENABLED,
	PID_SCENE_FLOOR_REFLECTION_LEVEL,
	PID_SCENE_FLOOR_ROUGHNESS,
	PID_SCENE_FLOOR_SHADOW_LEVEL,

	PID_CAMERA,
	PID_CAMERA_TARGET,
	PID_CAMERA_DISTANCE,
	PID_CAMERA_YAW,
	PID_CAMERA_PITCH,
	PID_CAMERA_ROLL,
	PID_CAMERA_PROJECTION,
	PID_CAMERA_FOV,
	PID_CAMERA_ASPECT,
	PID_CAMERA_Z_NEAR,
	PID_CAMERA_Z_FAR,
	PID_CAMERA_DEPTH_OF_FIELD,
	PID_CAMERA_F_STOP,
	PID_CAMERA_FOCUS_DISTANCE,
	PID_CAMERA_DIAPHRAGM_BLADES,
	PID_CAMERA_BOKEH_ROTATION,
	PID_CAMERA_GAMMA,

	PID_SNAPSHOT,
	PID_SNAPSHOT_NAME,
	PID_SNAPSHOT_HAS_CAMERA_STATE,
	PID_SNAPSHOT_HAS_VISIBILITY,
	PID_SNAPSHOT_HAS_TRANSFORMATIONS,
	PID_SNAPSHOT_HAS_ASSIGNED_MATERIALS,
	PID_SNAPSHOT_HAS_ENVIRONMENT,
	PID_SNAPSHOT_HAS_BACKGROUND,

	PID_NODE,
	PID_NODE_NAME,
	PID_NODE_VISIBLE,
	PID_NODE_POSITION,
	PID_NODE_ROTATION,
	PID_NODE_SCALE,

	PID_MESH_NODE_RENDER_LAYER,
	PID_RENDER_LAYER_NAME,

	PID_LIGHT_COLOR,
	PID_LIGHT_INTENSITY,
	PID_LIGHT_RADIUS,

	PID_DIRECTION_LIGHT_COLOR,
	PID_DIRECTION_LIGHT_INTENSITY,
	PID_DIRECTION_LIGHT_ANGULAR_SIZE,
	PID_DIRECTION_LIGHT_YAW,
	PID_DIRECTION_LIGHT_PITCH,

	PID_MATERIAL,
	PID_MATERIAL_NAME,
	PID_MATERIAL_GROUPS,
	PID_MATERIAL_BUMP,
	PID_MATERIAL_MEDIUM_TYPE,
	PID_MATERIAL_IOR,
	PID_MATERIAL_ABSORPTION_COLOR,
	PID_MATERIAL_ABSORPTION_ATTENUATION,
	PID_MATERIAL_EMISSION_COLOR,
	PID_MATERIAL_EMISSION_SCALE,
	PID_MATERIAL_SUBSURFACE_SCATTERING,
	PID_MATERIAL_SCATTERING_COLOR,
	PID_MATERIAL_SCATTERING_SCALE,
	PID_MATERIAL_SCATTERING_ASYMMETRY,
	PID_MATERIAL_PRIORITY,
	PID_MATERIAL_DOUBLE_SIDED,

	PID_GROUP,
	PID_GROUP_NAME,
	PID_GROUP_ENABLED,
	PID_GROUP_LAYERS,
	PID_GROUP_MASK,
	PID_GROUP_EMISSION,
	PID_GROUP_EMISSION_INTENSITY,

	PID_LAYER,
	PID_LAYER_NAME,
	PID_LAYER_ENABLED,
	PID_LAYER_MASK,
	PID_LAYER_TYPE,
	PID_LAYER_DIFFUSE_LAYER,
	PID_LAYER_DIFFUSE_COLOR,
	PID_LAYER_DIFFUSE_OPACITY,
	PID_LAYER_DIFFUSE_TRANSMISSION,
	PID_LAYER_DIFFUSE_TEXTURE_LAYER_MASK,
	PID_LAYER_EMISSIVE_LAYER,
	PID_LAYER_EMISSIVE_COLOR,
	PID_LAYER_EMISSIVE_LEVEL,
	PID_LAYER_SPECULAR_LAYER,
	PID_LAYER_REFLECTION,
	PID_LAYER_TRANSMISSION,
	PID_LAYER_IOR,
	PID_LAYER_REFLECTION_90_LEVEL,
	PID_LAYER_REFLECTION_90,
	PID_LAYER_ROUGHNESS,
	PID_LAYER_BUMP,
	PID_LAYER_ANISOTROPY,
	PID_LAYER_ANISOTROPY_ANGLE,
	PID_LAYER_THIN_FILM_INTERFERENCE,
	PID_LAYER_FILM_THICKNESS,
	PID_LAYER_MIN_FILM_THICKNESS,
	PID_LAYER_FILM_IOR,

	PID_TEXTURE,
	PID_TEXTURE_ENABLED,
	PID_TEXTURE_FILENAME,
	PID_TEXTURE_CROP,
	PID_TEXTURE_REPEAT,
	PID_TEXTURE_OFFSET,
	PID_TEXTURE_ROTATION,
	PID_TEXTURE_INVERT,
	PID_TEXTURE_WRAP_X,
	PID_TEXTURE_WRAP_Y,
	PID_TEXTURE_MAPPING,
	PID_TEXTURE_BRIGHTNESS,
	PID_TEXTURE_CONTRAST,
	PID_TEXTURE_GAMMA,
	PID_TEXTURE_NORMAL_MAP,

	PID_IOR_TYPE,
	PID_IOR_N,
	PID_IOR_K,
	PID_IOR_FILENAME,

	PID_FIT_TO_VIEW_JUST_SELECTED_OBJECTS,
	PID_FIT_TO_VIEW_INCLUDING_CHILDREN_OBJECTS,
	PID_FIT_TO_VIEW_KEEP_ASPECT,
	PID_FIT_TO_VIEW_PADDING,

	PID_UV_MAPPING_MAPPING,
	PID_UV_MAPPING_FIT_TO,
	PID_UV_MAPPING_CHANNEL,
	PID_UV_MAPPING_FLIP_U,
	PID_UV_MAPPING_FLIP_V,
	PID_UV_MAPPING_NORMALIZE,
	PID_UV_MAPPING_SCALE,
	PID_UV_MAPPING_REPEAT,

	PID_EDIT_NORMALS_CALCULATE_NORMALS,
	PID_EDIT_NORMALS_MAKE_EDGES,
	PID_EDIT_NORMALS_MAX_SOFT_ANGLE,
	PID_EDIT_NORMALS_FLIP_NORMALS,
	PID_EDIT_NORMALS_FLIP_FACING,

	PID_PIVOT_PARAMETERS_CALCULATE_PIVOT,
	PID_PIVOT_PARAMETERS_INCLUDING_CHILDREN_NODES,
	PID_PIVOT_PARAMETERS_PIVOT_X,
	PID_PIVOT_PARAMETERS_PIVOT_Y,
	PID_PIVOT_PARAMETERS_PIVOT_Z,

	PID_SNAPSHOT_INTERPOLATOR_TRANSITION_FRAME,
	PID_SNAPSHOT_INTERPOLATOR_TRANSITION_FRAME_COUNT,
	PID_SNAPSHOT_INTERPOLATOR_TRANSITION_EXPONENT,
	PID_SNAPSHOT_INTERPOLATOR_TRANSITION_MOTION_BLUR,
};

struct ModelSavingContext;
struct ModelLoadingContext;
class CoreInstance;

class IParameterOwner
{
public:
	virtual CoreInstance & core() const = 0;
	virtual void pushCommand(QUndoCommand *cmd) = 0;
	virtual void fireChanged(eParamId paramId) = 0;
};

#include "Parameters/ColorParameterImpl.h"
#include "Parameters/ScalarParameterImpl.h"
#include "Parameters/BooleanParameterImpl.h"
#include "Parameters/IntegerParameterImpl.h"
#include "Parameters/Vec2ParameterImpl.h"
#include "Parameters/Vec3ParameterImpl.h"
#include "Parameters/EnumParameterImpl.h"
#include "Parameters/StringParameterImpl.h"
#include "Parameters/FileNameParameterImpl.h"
