/*
 * Copyright (C) 2014, Petr Vevoda, Martin Sik (http://cgg.mff.cuni.cz/~sik/),
 * Tomas Davidovic (http://www.davidovic.cz), Iliyan Georgiev (http://www.iliyan.com/),
 * Jaroslav Krivanek (http://cgg.mff.cuni.cz/~jaroslav/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom
 * the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * (The above is MIT License: http://en.wikipedia.origin/wiki/MIT_License)
 */

#pragma once

#define UPBP_CAMERA_MAXVERTS	1001
#define UPBP_LIGHT_AVGVERTS		20

#include "HashGrid.h"
#include "UPBPLightVertex.h"
#include "PathWeight.h"
#include "PhBeams.h"
#include "Bre.h"

class UPBP final : public BaseRenderer
{
	// The sole point of this structure is to make carrying around the ray baggage easier.
	struct SubPathState
	{
		vec3		mOrigin;			// Path origin
		vec3		mDirection;			// Where to go next
		vec3		mThroughput;		// Path throughput
		uint32_t	mPathLength : 30;	// Number of path segments, including this
		bool		mIsFiniteLight;		// Just generated by finite light
		bool		mSpecularPath;		// All scattering events so far were specular
		bool		mLastSpecular;		// Last sampled event was specular
		float		mLastPdfWInv;		// PDF of the last sampled direction

		const MisData *	mCameraVerticesMisData;	// Stored MIS data for camera vertices (we don't need store whole vertices as for light paths)
		BoundaryStack	mBoundaryStack;			// Stack of crossed boundaries
	};

	// Range query used for PPM, BPM, and UPBP. When HashGrid finds a vertex
	// within range -- process() is called and vertex
	// merging is performed. BSDF of the camera vertex is used.
	class RangeQuery
	{
	public:

		RangeQuery(const UPBP         &aUPBP,
				   const vec3         &aCameraPosition,
				   const BSDF         &aCameraBsdf,
				   const SubPathState &aCameraState)
			: mUPBP(aUPBP)
			, mCameraPosition(aCameraPosition)
			, mCameraBsdf(aCameraBsdf)
			, mCameraState(aCameraState)
			, mContrib(0.f)
		{}

		const vec3 & GetPosition() const { return mCameraPosition; }

		const vec3 & GetContrib() const { return mContrib; }

		void process(const UPBPLightVertex& aLightVertex)
		{
			// We store all light vertices but not all can be used for merging (delta and light)
			if (!aLightVertex.mConnectable)
				return;

			// Use only vertices with same location (on surface/in medium)
			assert(aLightVertex.mInMedium == mCameraBsdf.isInMedium());

			// Reject if full path length below/above min/max path length
			if (aLightVertex.mPathLength + mCameraState.mPathLength > mUPBP.m_maxPathLength)
				return;

			// Retrieve light incoming direction in world coordinates
			const vec3 lightDirection = aLightVertex.mBSDF.worldDirFix();

			float cosCamera, cameraBsdfDirPdfW, cameraBsdfRevPdfW, sinTheta;
			const vec3 cameraBsdfFactor = mCameraBsdf.evaluate(lightDirection, cosCamera, &cameraBsdfDirPdfW,
															   &cameraBsdfRevPdfW, &sinTheta);

			if (isBlack(cameraBsdfFactor))
				return;

			cameraBsdfDirPdfW *= mCameraBsdf.continuationProbability();
			assert(cameraBsdfDirPdfW > 0);

			// Even though this is PDF from camera BSDF, the continuation probability
			// must come from light BSDF, because that would govern it if light path
			// actually continued
			cameraBsdfRevPdfW *= aLightVertex.mBSDF.continuationProbability();
			assert(cameraBsdfRevPdfW > 0);

			// MIS weight
			float misWeight = 1.0f;
			if (mUPBP.mAlgorithm != kPPM) {
				const float misWeightFactorInv = 1.0f / (aLightVertex.mInMedium ? aLightVertex.mMisData.mPP3DMisWeightFactor : aLightVertex.mMisData.mSurfMisWeightFactor);
				const float wCamera = mUPBP.accumulateCameraPathWeight2(mCameraState.mPathLength, misWeightFactorInv, sinTheta, aLightVertex.mMisData.mRaySamplePdfInv, aLightVertex.mMisData.mRaySamplePdfsRatio, cameraBsdfRevPdfW, mCameraState.mCameraVerticesMisData);
				const float wLight = mUPBP.accumulateLightPathWeight2(aLightVertex.mPathIdx, aLightVertex.mPathLength, misWeightFactorInv, 0, 0, 0, cameraBsdfDirPdfW, aLightVertex.mInMedium ? PP3D : SURF, false);
				misWeight = 1.f / (wLight + wCamera);
			}

			const vec3 mult = cameraBsdfFactor * aLightVertex.mThroughput;
			mContrib += misWeight * mult;
		}

	private:

		const UPBP         &mUPBP;
		const vec3         &mCameraPosition;
		const BSDF         &mCameraBsdf;
		const SubPathState &mCameraState;
		vec3               mContrib;
	};

	struct CameraPhoton
	{
		vec3		color;
		uint16_t	x, y;
	};
	typedef std::vector<CameraPhoton>	CameraPhotonsArray;

public:

	enum AlgorithmType {
		kLT = 0,   // light tracing
		kPTdir,    // direct path tracing
		kPTls,     // path tracing with light sampling
		kPTmis,    // path tracing with MIS
		kBPT,      // bidirectional path tracing
		kPPM,      // camera and light vertices merged on first non-specular surface from camera (cannot handle mixed specular + non-specular materials)
		kBPM,      // camera and light vertices merged on along full path
		kVCM,      // vertex connection and merging
		kCustom    // combination of techniques (BPT, SURF, PP3D, PB2D, BB1D) specified using flags
	};

	UPBP(Scene &					aScene,
		 const AlgorithmType		aAlgorithm,
		 const uint					aEstimatorTechniques,
		 const RadiusCalculation	aPB2DRadiusCalculation,
		 const int					aPB2DRadiusKNN,
		 const BeamType				aQueryBeamType,
		 const RadiusCalculation	aBB1DRadiusCalculation,
		 const int					aBB1DRadiusKNN,
		 const BeamType				aPhotonBeamType,
		 const float				aBB1DBeamStorageFactor,
		 const float				aRefPathCountPerIter,
		 const float				aPathCountPerIter,
		 const float				aMinDistToMed,
		 const size_t				aMaxMemoryPerThread,
		 const int					aBaseSeed = 1234);

	void runIteration(int aIteration);

private:

	void beginIteration() override;
	void endIteration() override;

	void traceLightPathsThreadFunc(int threadIndex);
	void traceLightPath(int aPathIdx, std::vector<UPBPLightVertex> & oLightVertices, CameraPhotonsArray & oCameraPhotons, PhotonBeamsArray & oPhotonBeamsArray, Sampler & sampler);
	void traceCameraPath(TraceResult & res, TraceContext & ctx) override;
	void buildAccelerationStructures();
	void buildSurfHashGrid();
	void buildPP3DHashGrid();
	void buildPB2DEmbreeBre();
	void buildBB1DPhotonBeams();

	//////////////////////////////////////////////////////////////////////////
	// Camera tracing methods
	//////////////////////////////////////////////////////////////////////////

	// Generates new camera sample given a pixel index
	void generateCameraSample(const TraceContext & aCtx, SubPathState & oCameraState);

	// Returns the radiance of a light source when hit by a random ray,
	// multiplied by MIS weight. Can be used for both Background and Area lights.
	vec3 getLightRadiance(const AbstractLight	*aLight,
						  const SubPathState	&aCameraState,
						  const Ray				&aRay,
						  const vec3			*aRadiance = nullptr) const;

	// Connects camera vertex to randomly chosen light point.
	// Returns emitted radiance multiplied by path MIS weight.
	// Has to be called AFTER updating the MIS quantities.
	vec3 directIllumination(const SubPathState	&aCameraState,
							const vec3			&aHitpoint,
							const BSDF			&aCameraBSDF,
							const TraceContext	&aCtx);

	// Connects an eye and a light vertex. Result multiplied by MIS weight, but
	// not multiplied by vertex throughputs. Has to be called AFTER updating MIS
	// constants. 'direction' is FROM eye TO light vertex.
	vec3 connectVertices(const UPBPLightVertex	&aLightVertex,
						 const BSDF				&aCameraBSDF,
						 const vec3				&aCameraHitpoint,
						 const SubPathState		&aCameraState,
						 const TraceContext	&aCtx);

	// Accumulates PDF ratios of all sampling techniques along path originally sampled from camera
	inline float accumulateCameraPathWeight2(const int   aPathLength,
											 const float aLastRevPdfA,
											 const float aLastSinTheta,
											 const float aLastRaySampleRevPdfInv,
											 const float aLastRaySampleRevPdfsRatio,
											 const float aNextToLastPartialRevPdfW,
											 const MisData * mCameraVerticesMisData) const
	{
		return accumulateCameraPathWeight(aPathLength, aLastRevPdfA, aLastSinTheta, aLastRaySampleRevPdfInv, aLastRaySampleRevPdfsRatio, aNextToLastPartialRevPdfW, mQueryBeamType, mPhotonBeamType, mEstimatorTechniques, mCameraVerticesMisData);
	}

	//////////////////////////////////////////////////////////////////////////
	// Light tracing methods
	//////////////////////////////////////////////////////////////////////////

	// Samples light emission
	bool generateLightSample(int aPathIdx, SubPathState &oLightState, std::vector<UPBPLightVertex> & oLightVertices, Sampler & sampler);

	// Computes contribution of light sample to camera by splatting is onto the
	// framebuffer. Multiplies by throughput (obviously, as nothing is returned).
	void connectToCamera(const UPBPLightVertex  *aLightVertices,
						 const SubPathState		&aLightState,
						 const vec3				&aHitpoint,
						 const BSDF				&aLightBSDF,
						 const float			aRaySampleRevPdfsRatio,
						 const TraceContext	&aCtx,
						 CameraPhotonsArray		&oCameraPhotons);

	// Adds beams to beams array
	void addBeams(const Ray &aRay,
				  const vec3 &aThroughput,
				  const VolumeSegments & mVolumeSegments,
				  UPBPLightVertex *aLightVertex,
				  const uint aRaySamplingFlags,
				  const float aLastPdfWInv,
				  PhotonBeamsArray & oPhotonBeamsArray);

	// Accumulates PDF ratios of all sampling techniques along path originally sampled from light
	inline float accumulateLightPathWeight2(const int   aPathIndex,
											const int   aPathLength,
											const float aLastRevPdfA,
											const float aLastSinTheta,
											const float aLastRaySampleRevPdfInv,
											const float aLastRaySampleRevPdfsRatio,
											const float aNextToLastPartialRevPdfW,
											const uint  aCurrentlyEvaluatedTechnique,
											const bool  aCameraConnection) const
	{
		return AccumulateLightPathWeight(mLightVertices.data() + mPathSegments[aPathIndex].begin, aPathLength, aLastRevPdfA, aLastSinTheta, aLastRaySampleRevPdfInv, aLastRaySampleRevPdfsRatio, aNextToLastPartialRevPdfW, aCurrentlyEvaluatedTechnique, mQueryBeamType, mPhotonBeamType, mEstimatorTechniques, aCameraConnection);
	}

	//////////////////////////////////////////////////////////////////////////
	// Common methods
	//////////////////////////////////////////////////////////////////////////

	// MIS power, we use balance heuristic
	float mis(float aPdf) const
	{
		//return std::pow(aPdf, /*power*/);
		return aPdf;
	}

	// MIS weight for 2 PDFs
	float mis2(float aSamplePdf, float aOtherPdf) const
	{
		return mis(aSamplePdf) / (mis(aSamplePdf) + mis(aOtherPdf));
	}

	// Samples a scattering direction camera/light sample according to BSDF.
	// Returns false for termination
	bool sampleScattering(const BSDF	&aBSDF,
						  const vec3	&aHitPoint,
						  const Isect	&aIsect,
						  SubPathState	&aoState,
						  MisData		&aoCurrentMisData,
						  MisData		&aoPreviousMisData,
						  TraceContext &ctx);

private:
	// Flags controlling computation according to the selected algorithm type
	bool mTraceLightPaths;
	bool mTraceCameraPaths;
	bool mConnectToCamera;
	bool mConnectToCameraFromSurf;
	bool mConnectToLightSource;
	bool mConnectToLightVertices;
	bool mMergeWithLightVerticesSurf;
	bool mMergeWithLightVerticesPP3D;
	bool mMergeWithLightVerticesPB2D;
	bool mMergeWithLightVerticesBB1D;
	float mImagePlaneDist;

	// Flags of used estimator techniques (used when calling methods from outside)
	uint mEstimatorTechniques;

	// SURF
	float		m_radiusSurf;
	float		mSurfMisWeightFactor; // Weight factor of SURF
	float		mSurfNormalization;   // 1 / (Pi * surf_radius^2 * light_path_count)
	HashGrid	mSurfHashGrid;        // Hashgrid used for photon lookup
	float		mSurfRadiusInitial;   // Initial merging radius
	float		mSurfRadiusAlpha;     // Radius reduction rate parameter

	// PP3D
	float		m_radiusPP3D;
	float		mPP3DMisWeightFactor;  // Weight factor of PP3D
	float		mPP3DNormalization;    // 1 / (4/3 * Pi * pp3d_radius^3 * light_path_count)
	HashGrid	mPP3DHashGrid;         // Hashgrid used for photon lookup
	float		mPP3DRadiusInitial;    // Initial merging radius
	float		mPP3DRadiusAlpha;      // Radius reduction rate parameter

	// PB2D
	float				m_radiusPB2D;
	float				mPB2DMisWeightFactor;   // Weight factor of PB2D
	float				mPB2DNormalization;     // 1 / light_path_count
	EmbreeBre			mPB2DEmbreeBre;         // Encapsulates storing photons and evaluating contributions of their intersections with beams
	float				mPB2DRadiusInitial;     // Initial merging radius
	float				mPB2DRadiusAlpha;       // Radius reduction rate parameter
	RadiusCalculation	mPB2DRadiusCalculation; // Type of photon radius calculation
	int					mPB2DRadiusKNN;	      // Value x means that x-th closest photon will be used for calculation of radius of the current photon
	BeamType			mQueryBeamType;         // Short/long beam

	// BB1D
	float				m_radiusBB1D;
	float				mBB1DMisWeightFactor;       // Weight factor of BB1D
	float				mBB1DNormalization;         // 1 / bb1d_light_path_count
	PhotonBeamsEvaluator mBB1DPhotonBeams;           // Encapsulates evaluating contributions of their intersections with beams
	float				mBB1DRadiusInitial;         // Initial merging radius
	float				mBB1DRadiusAlpha;           // Radius reduction rate parameter
	RadiusCalculation	mBB1DRadiusCalculation;     // Type of photon radius calculation
	int					mBB1DRadiusKNN;             // Value x means that x-th closest beam vertex will be used for calculation of cone radius at the current beam vertex
	float				mBB1DMinMFP;                // Minimum MFP of medium to store photon beams in it
	BeamType			mPhotonBeamType;            // Short/long beam
	float				mBB1DUsedLightSubPathCount; // First mBB1DUsedLightSubPathCount out of mLightSubPathCount light paths will generate photon beams
	float				mBB1DBeamStorageFactor;     // Factor used for computation of minimum MFP of media where photon beams are used. The lower it is the denser media will use photon beams.

	float mScreenPixelCount;         // Number of pixels
	float mLightSubPathCount;        // Number of light sub-paths
	float mRefPathCountPerIter;      // Reference number of paths per iteration
	float mPathCountPerIter;         // Number of paths per iteration
	int		m_viewportWidth, m_viewportHeight;
	vec2	m_viewportToScreen[2];

	size_t mLightVertexCount;
	size_t mPhotonBeamsCount;
	std::atomic_size_t mLightVerticesOnSurfaceCount; // Number of light vertices located on surface
	std::atomic_size_t mLightVerticesInMediumCount;  // Number of light vertices located in medium

	std::atomic_size_t	m_lightPathIndex;
	std::atomic_size_t	m_lightVertexIndex;

	std::vector<UPBPLightVertex>		mLightVertices;				// Stored light vertices
	PhotonBeamsArray					mPhotonBeamsArray;			// Stored photon beams
	std::vector< PhotonBeamsArray >		mThreadPhotonBeamsArray;	// Stored photon beams
	std::vector< CameraPhotonsArray >	mThreadCameraPhotons;		// Stored camera photons

	// For light path belonging to pixel index [x] it stores
	// where it's light vertices end (begin is at [x-1])
	std::vector<PathSegment>			mPathSegments;

	// Used algorithm
	AlgorithmType mAlgorithm;

	// Minimum distance from camera at which scattering events in media can occur
	float mMinDistToMed;

	int mBaseSeed;

	// Maximum memory for light vertices in thread
	size_t mMaxMemoryPerThread;
};
